site_name: Particle Magic — GPU Compute Simulation
theme:
  name: material
  palette:
    scheme: slate
    primary: deep purple
    accent: purple
  features:
    - content.code.copy
    - navigation.expand

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight
  - pymdownx.superfences
  - admonition
  - tables

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Technical Report: index.md